language: php

php:
  - '7.2'
  - '7.3'

before_script: cd $TRAVIS_BUILD_DIR && COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit tests